"""initial schema

Revision ID: 18476fc943d8
Revises:
Create Date: 2026-08-08 19:31:39.872053+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "18476fc943d8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum("CA_FIRM", "COMPANY", name="orgtype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PRIVATE_LIMITED",
                "PUBLIC_LIMITED",
                "ONE_PERSON_COMPANY",
                "LLP",
                "PARTNERSHIP",
                "PROPRIETORSHIP",
                "TRUST",
                "SOCIETY",
                "SECTION_8",
                "FOREIGN_COMPANY",
                "HUF",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("gstin", sa.String(length=255), nullable=True),
        sa.Column("gstin_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("pan", sa.String(length=255), nullable=True),
        sa.Column("pan_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("cin", sa.String(length=255), nullable=True),
        sa.Column("cin_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("llpin", sa.String(length=32), nullable=True),
        sa.Column("firm_registration_no", sa.String(length=32), nullable=True),
        sa.Column("tan", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("annual_turnover_paise", sa.BigInteger(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("incorporation_date", sa.Date(), nullable=True),
        sa.Column("financial_year_end_month", sa.Integer(), nullable=False),
        sa.Column("is_listed", sa.Boolean(), nullable=False),
        sa.Column("has_foreign_investment", sa.Boolean(), nullable=False),
        sa.Column("handles_personal_data", sa.Boolean(), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "plan_tier",
            sa.Enum(
                "SMB",
                "PROFESSIONAL",
                "CA_FIRM",
                "ENTERPRISE",
                name="plantier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cin_fingerprint", "deleted_at", name="uq_organizations_cin"),
        sa.UniqueConstraint("gstin_fingerprint", "deleted_at", name="uq_organizations_gstin"),
    )
    op.create_index(
        op.f("ix_organizations_cin_fingerprint"), "organizations", ["cin_fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_gstin_fingerprint"),
        "organizations",
        ["gstin_fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_organizations_industry"), "organizations", ["industry"], unique=False)
    op.create_index(
        op.f("ix_organizations_pan_fingerprint"), "organizations", ["pan_fingerprint"], unique=False
    )
    op.create_index(op.f("ix_organizations_state"), "organizations", ["state"], unique=False)
    op.create_index(
        "ix_organizations_type_active", "organizations", ["type", "is_active"], unique=False
    )
    op.create_table(
        "regulatory_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("reference_no", sa.String(length=255), nullable=True),
        sa.Column("published_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "regulation",
            sa.Enum(
                "GST",
                "INCOME_TAX",
                "RBI",
                "SEBI",
                "MCA",
                "FEMA",
                "LABOR",
                "DPDP",
                name="regulation",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "domains_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "impact_level",
            sa.Enum(
                "CRITICAL",
                "HIGH",
                "MEDIUM",
                "LOW",
                "NONE",
                name="impactlevel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "analysis_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "affected_entity_types_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "affected_states_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "affected_obligation_codes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("action_required", sa.Text(), nullable=True),
        sa.Column("compliance_deadline", sa.Date(), nullable=True),
        sa.Column("is_analysed", sa.Boolean(), nullable=False),
        sa.Column("analysed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "reference_no", "title", "deleted_at", name="uq_reg_updates_source_ref"
        ),
    )
    op.create_index(
        "ix_reg_updates_pending",
        "regulatory_updates",
        ["is_analysed", "published_date"],
        unique=False,
    )
    op.create_index(
        "ix_reg_updates_published",
        "regulatory_updates",
        ["published_date", "impact_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_updates_deleted_at"), "regulatory_updates", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_regulatory_updates_impact_level"),
        "regulatory_updates",
        ["impact_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_updates_published_date"),
        "regulatory_updates",
        ["published_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_updates_reference_no"),
        "regulatory_updates",
        ["reference_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_updates_regulation"), "regulatory_updates", ["regulation"], unique=False
    )
    op.create_index(
        op.f("ix_regulatory_updates_source"), "regulatory_updates", ["source"], unique=False
    )
    op.create_table(
        "compliance_obligations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "regulation",
            sa.Enum(
                "GST",
                "INCOME_TAX",
                "RBI",
                "SEBI",
                "MCA",
                "FEMA",
                "LABOR",
                "DPDP",
                name="regulation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("filing_type", sa.String(length=64), nullable=True),
        sa.Column("section", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("authority", sa.String(length=128), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "HALF_YEARLY",
                "ANNUAL",
                "EVENT_BASED",
                "ONE_TIME",
                name="frequency",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("due_day", sa.Integer(), nullable=True),
        sa.Column("due_month", sa.Integer(), nullable=True),
        sa.Column("offset_days", sa.Integer(), nullable=True),
        sa.Column("period_offset", sa.Integer(), nullable=False),
        sa.Column(
            "entity_types_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "states_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "industries_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("min_turnover_paise", sa.BigInteger(), nullable=True),
        sa.Column("max_turnover_paise", sa.BigInteger(), nullable=True),
        sa.Column("min_employees", sa.Integer(), nullable=True),
        sa.Column("requires_listed", sa.Boolean(), nullable=True),
        sa.Column("requires_foreign_investment", sa.Boolean(), nullable=True),
        sa.Column("requires_personal_data", sa.Boolean(), nullable=True),
        sa.Column("penalty_description", sa.Text(), nullable=True),
        sa.Column("penalty_per_day_paise", sa.BigInteger(), nullable=True),
        sa.Column("penalty_max_paise", sa.BigInteger(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "code", "deleted_at", name="uq_obligations_org_code"
        ),
    )
    op.create_index(
        op.f("ix_compliance_obligations_code"), "compliance_obligations", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_obligations_deleted_at"),
        "compliance_obligations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_obligations_filing_type"),
        "compliance_obligations",
        ["filing_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_obligations_organization_id"),
        "compliance_obligations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_obligations_regulation"),
        "compliance_obligations",
        ["regulation"],
        unique=False,
    )
    op.create_index(
        "ix_obligations_regulation_active",
        "compliance_obligations",
        ["regulation", "is_active"],
        unique=False,
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("principal_ref", sa.String(length=255), nullable=False),
        sa.Column("principal_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=False),
        sa.Column("purpose_description", sa.Text(), nullable=True),
        sa.Column(
            "data_categories_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("notice_version", sa.String(length=32), nullable=False),
        sa.Column("notice_text", sa.Text(), nullable=True),
        sa.Column("notice_language", sa.String(length=16), nullable=False),
        sa.Column("is_granted", sa.Boolean(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collection_method", sa.String(length=32), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "principal_fingerprint",
            "purpose",
            "notice_version",
            "deleted_at",
            name="uq_consent_principal_purpose_version",
        ),
    )
    op.create_index(
        "ix_consent_org_active", "consent_records", ["organization_id", "is_granted"], unique=False
    )
    op.create_index(
        "ix_consent_org_principal",
        "consent_records",
        ["organization_id", "principal_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_deleted_at"), "consent_records", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_consent_records_org_created",
        "consent_records",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_organization_id"),
        "consent_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_principal_fingerprint"),
        "consent_records",
        ["principal_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_purpose"), "consent_records", ["purpose"], unique=False
    )
    op.create_table(
        "data_map_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_name", sa.String(length=255), nullable=False),
        sa.Column("system_type", sa.String(length=64), nullable=True),
        sa.Column("owner_team", sa.String(length=128), nullable=True),
        sa.Column("data_category", sa.String(length=64), nullable=False),
        sa.Column(
            "data_fields_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=False),
        sa.Column("legal_basis", sa.String(length=64), nullable=False),
        sa.Column("retention_period_days", sa.Integer(), nullable=True),
        sa.Column("is_transferred_abroad", sa.Boolean(), nullable=False),
        sa.Column(
            "transfer_countries_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "processors_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("estimated_record_count", sa.Integer(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "system_name",
            "data_category",
            "deleted_at",
            name="uq_datamap_system_category",
        ),
    )
    op.create_index(
        op.f("ix_data_map_entries_data_category"),
        "data_map_entries",
        ["data_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_map_entries_deleted_at"), "data_map_entries", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_data_map_entries_org_created",
        "data_map_entries",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_map_entries_organization_id"),
        "data_map_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_datamap_org_sensitive",
        "data_map_entries",
        ["organization_id", "is_sensitive"],
        unique=False,
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "regulation",
            sa.Enum(
                "GST",
                "INCOME_TAX",
                "RBI",
                "SEBI",
                "MCA",
                "FEMA",
                "LABOR",
                "DPDP",
                name="regulation",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("filing_type", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "template_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("body_template", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("statutory_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "code", "version", "deleted_at", name="uq_templates_code_version"
        ),
    )
    op.create_index(op.f("ix_templates_code"), "templates", ["code"], unique=False)
    op.create_index(op.f("ix_templates_deleted_at"), "templates", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_templates_filing_type"), "templates", ["filing_type"], unique=False)
    op.create_index(
        "ix_templates_lookup", "templates", ["code", "is_active", "version"], unique=False
    )
    op.create_index(
        op.f("ix_templates_organization_id"), "templates", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_templates_regulation"), "templates", ["regulation"], unique=False)
    op.create_index(
        "ix_templates_regulation_active", "templates", ["regulation", "is_active"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "COMPLIANCE_MANAGER",
                "STAFF",
                "READ_ONLY",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.String(length=255), nullable=True),
        sa.Column("totp_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", "deleted_at", name="uq_users_org_email"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        "ix_users_org_created", "users", ["organization_id", "created_at"], unique=False
    )
    op.create_index("ix_users_org_role", "users", ["organization_id", "role"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "audit_trails",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "SOFT_DELETE",
                "READ",
                "LOGIN",
                "LOGIN_FAILED",
                "LOGOUT",
                "SUBMIT",
                "APPROVE",
                "REJECT",
                "GENERATE",
                "EXPORT",
                "ROLE_CHANGE",
                "NOTIFY",
                name="auditaction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "before_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("prev_checksum", sa.String(length=64), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sequence", name="uq_audit_org_sequence"),
    )
    op.create_index(
        "ix_audit_org_entity",
        "audit_trails",
        ["organization_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_org_sequence", "audit_trails", ["organization_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_audit_org_timestamp", "audit_trails", ["organization_id", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_audit_trails_action"), "audit_trails", ["action"], unique=False)
    op.create_index(op.f("ix_audit_trails_checksum"), "audit_trails", ["checksum"], unique=False)
    op.create_index(op.f("ix_audit_trails_entity_id"), "audit_trails", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_trails_entity_type"), "audit_trails", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_trails_organization_id"), "audit_trails", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_trails_request_id"), "audit_trails", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_trails_timestamp"), "audit_trails", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_trails_user_id"), "audit_trails", ["user_id"], unique=False)
    op.create_table(
        "breach_incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("affected_principals_count", sa.Integer(), nullable=True),
        sa.Column(
            "affected_data_categories_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "affected_systems_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("dpb_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dpb_reference", sa.String(length=128), nullable=True),
        sa.Column("dpb_notification_text", sa.Text(), nullable=True),
        sa.Column("principals_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("principals_notification_text", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reported_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reported_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "reference", "deleted_at", name="uq_breach_org_reference"
        ),
    )
    op.create_index(
        op.f("ix_breach_incidents_deleted_at"), "breach_incidents", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_breach_incidents_org_created",
        "breach_incidents",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_breach_incidents_organization_id"),
        "breach_incidents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_breach_incidents_status"), "breach_incidents", ["status"], unique=False
    )
    op.create_index(
        "ix_breach_org_detected",
        "breach_incidents",
        ["organization_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_breach_org_status", "breach_incidents", ["organization_id", "status"], unique=False
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ca_firm_id", sa.Integer(), nullable=False),
        sa.Column("client_org_id", sa.Integer(), nullable=False),
        sa.Column("engagement_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column("retainer_paise", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ca_firm_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["client_org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ca_firm_id", "client_org_id", "deleted_at", name="uq_clients_firm_client"
        ),
    )
    op.create_index(
        op.f("ix_clients_assigned_user_id"), "clients", ["assigned_user_id"], unique=False
    )
    op.create_index(op.f("ix_clients_ca_firm_id"), "clients", ["ca_firm_id"], unique=False)
    op.create_index(op.f("ix_clients_client_org_id"), "clients", ["client_org_id"], unique=False)
    op.create_index(op.f("ix_clients_deleted_at"), "clients", ["deleted_at"], unique=False)
    op.create_index("ix_clients_firm_status", "clients", ["ca_firm_id", "status"], unique=False)
    op.create_table(
        "data_subject_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("request_type", sa.String(length=32), nullable=False),
        sa.Column("principal_ref", sa.String(length=255), nullable=False),
        sa.Column("principal_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("principal_name", sa.String(length=255), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference", "deleted_at", name="uq_dsr_org_ref"),
    )
    op.create_index(
        op.f("ix_data_subject_requests_assigned_to_id"),
        "data_subject_requests",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_deleted_at"),
        "data_subject_requests",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_due_date"),
        "data_subject_requests",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        "ix_data_subject_requests_org_created",
        "data_subject_requests",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_organization_id"),
        "data_subject_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_principal_fingerprint"),
        "data_subject_requests",
        ["principal_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_request_type"),
        "data_subject_requests",
        ["request_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_subject_requests_status"), "data_subject_requests", ["status"], unique=False
    )
    op.create_index(
        "ix_dsr_org_status_due",
        "data_subject_requests",
        ["organization_id", "status", "due_date"],
        unique=False,
    )
    op.create_table(
        "filings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sa.Integer(), nullable=False),
        sa.Column(
            "regulation",
            sa.Enum(
                "GST",
                "INCOME_TAX",
                "RBI",
                "SEBI",
                "MCA",
                "FEMA",
                "LABOR",
                "DPDP",
                name="regulation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("filing_type", sa.String(length=64), nullable=True),
        sa.Column("period_key", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("extended_due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "DRAFT",
                "IN_REVIEW",
                "APPROVED",
                "SUBMITTED",
                "ACKNOWLEDGED",
                "REJECTED",
                "LATE_FILED",
                "NOT_APPLICABLE",
                name="filingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("ai_model", sa.String(length=128), nullable=True),
        sa.Column("ai_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_confidence", sa.Integer(), nullable=True),
        sa.Column("ai_notes", sa.Text(), nullable=True),
        sa.Column("prepared_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column("acknowledgement_no", sa.String(length=128), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("tax_payable_paise", sa.BigInteger(), nullable=True),
        sa.Column("tax_paid_paise", sa.BigInteger(), nullable=True),
        sa.Column("penalty_paise", sa.BigInteger(), nullable=True),
        sa.Column("late_fee_paise", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["compliance_obligations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prepared_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "obligation_id",
            "period_key",
            "deleted_at",
            name="uq_filings_org_obligation_period",
        ),
    )
    op.create_index(
        op.f("ix_filings_acknowledgement_no"), "filings", ["acknowledgement_no"], unique=False
    )
    op.create_index(op.f("ix_filings_deleted_at"), "filings", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_filings_due_date"), "filings", ["due_date"], unique=False)
    op.create_index(op.f("ix_filings_filing_type"), "filings", ["filing_type"], unique=False)
    op.create_index(op.f("ix_filings_obligation_id"), "filings", ["obligation_id"], unique=False)
    op.create_index(
        "ix_filings_org_created", "filings", ["organization_id", "created_at"], unique=False
    )
    op.create_index("ix_filings_org_due", "filings", ["organization_id", "due_date"], unique=False)
    op.create_index(
        "ix_filings_org_status_due",
        "filings",
        ["organization_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_filings_organization_id"), "filings", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_filings_period_key"), "filings", ["period_key"], unique=False)
    op.create_index(op.f("ix_filings_prepared_by_id"), "filings", ["prepared_by_id"], unique=False)
    op.create_index(op.f("ix_filings_regulation"), "filings", ["regulation"], unique=False)
    op.create_index(op.f("ix_filings_reviewed_by_id"), "filings", ["reviewed_by_id"], unique=False)
    op.create_index(op.f("ix_filings_status"), "filings", ["status"], unique=False)
    op.create_index(op.f("ix_filings_template_id"), "filings", ["template_id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("whatsapp_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=32), nullable=True),
        sa.Column("sms_number", sa.String(length=32), nullable=True),
        sa.Column(
            "reminder_offsets_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", "deleted_at", name="uq_notif_pref_org_user"
        ),
    )
    op.create_index(
        op.f("ix_notification_preferences_deleted_at"),
        "notification_preferences",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_preferences_org_created",
        "notification_preferences",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_organization_id"),
        "notification_preferences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "WHATSAPP",
                "EMAIL",
                "SMS",
                "IN_APP",
                name="notificationchannel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("subject", sa.String(length=512), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "FAILED",
                "SKIPPED",
                name="notificationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("reminder_offset_days", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_channel"), "notifications", ["channel"], unique=False)
    op.create_index(
        op.f("ix_notifications_deleted_at"), "notifications", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_notifications_entity", "notifications", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_kind"), "notifications", ["kind"], unique=False)
    op.create_index(
        "ix_notifications_org_created",
        "notifications",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_org_status", "notifications", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_notifications_retry", "notifications", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "organization_obligations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sa.Integer(), nullable=False),
        sa.Column("is_applicable_override", sa.Boolean(), nullable=True),
        sa.Column("engine_verdict", sa.Boolean(), nullable=True),
        sa.Column("engine_reason", sa.Text(), nullable=True),
        sa.Column(
            "frequency_override",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "HALF_YEARLY",
                "ANNUAL",
                "EVENT_BASED",
                "ONE_TIME",
                name="frequency",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("due_day_override", sa.Integer(), nullable=True),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["compliance_obligations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "obligation_id", "deleted_at", name="uq_org_obligation"
        ),
    )
    op.create_index(
        "ix_org_obligations_org_created",
        "organization_obligations",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_obligations_deleted_at"),
        "organization_obligations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_obligations_obligation_id"),
        "organization_obligations",
        ["obligation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_obligations_organization_id"),
        "organization_obligations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_obligations_owner_user_id"),
        "organization_obligations",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "privacy_impact_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("processing_activity", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "answers_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_level", sa.String(length=16), nullable=True),
        sa.Column("risk_rationale", sa.Text(), nullable=True),
        sa.Column("ai_model", sa.String(length=128), nullable=True),
        sa.Column(
            "mitigations_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("residual_risk", sa.String(length=16), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_date", sa.Date(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pia_org_status",
        "privacy_impact_assessments",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_privacy_impact_assessments_deleted_at"),
        "privacy_impact_assessments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_privacy_impact_assessments_org_created",
        "privacy_impact_assessments",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_privacy_impact_assessments_organization_id"),
        "privacy_impact_assessments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_privacy_impact_assessments_status"),
        "privacy_impact_assessments",
        ["status"],
        unique=False,
    )
    op.create_table(
        "regulatory_impacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column(
            "impact_level",
            sa.Enum(
                "CRITICAL",
                "HIGH",
                "MEDIUM",
                "LOW",
                "NONE",
                name="impactlevel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("action_required", sa.Text(), nullable=True),
        sa.Column("action_deadline", sa.Date(), nullable=True),
        sa.Column(
            "affected_obligation_ids_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by_id", sa.Integer(), nullable=True),
        sa.Column("is_notified", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["acknowledged_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["update_id"], ["regulatory_updates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "update_id", "deleted_at", name="uq_impact_org_update"
        ),
    )
    op.create_index(
        "ix_impacts_org_level",
        "regulatory_impacts",
        ["organization_id", "impact_level"],
        unique=False,
    )
    op.create_index(
        "ix_impacts_org_open",
        "regulatory_impacts",
        ["organization_id", "is_acknowledged"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_impacts_deleted_at"), "regulatory_impacts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_regulatory_impacts_impact_level"),
        "regulatory_impacts",
        ["impact_level"],
        unique=False,
    )
    op.create_index(
        "ix_regulatory_impacts_org_created",
        "regulatory_impacts",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_impacts_organization_id"),
        "regulatory_impacts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regulatory_impacts_update_id"), "regulatory_impacts", ["update_id"], unique=False
    )
    op.create_table(
        "client_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("client_org_id", sa.Integer(), nullable=False),
        sa.Column(
            "granted_role",
            sa.Enum(
                "ADMIN",
                "COMPLIANCE_MANAGER",
                "STAFF",
                "READ_ONLY",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_id", "deleted_at", name="uq_assignment_user_client"),
    )
    op.create_index(
        op.f("ix_client_assignments_client_id"), "client_assignments", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_assignments_client_org_id"),
        "client_assignments",
        ["client_org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_assignments_deleted_at"), "client_assignments", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_client_assignments_user_id"), "client_assignments", ["user_id"], unique=False
    )
    op.create_index(
        "ix_client_assignments_user_org",
        "client_assignments",
        ["user_id", "client_org_id"],
        unique=False,
    )
    op.create_table(
        "deadlines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "reminders_sent_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("is_satisfied", sa.Boolean(), nullable=False),
        sa.Column("satisfied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filing_id", "deleted_at", name="uq_deadlines_filing"),
    )
    op.create_index(op.f("ix_deadlines_deleted_at"), "deadlines", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_deadlines_due_date"), "deadlines", ["due_date"], unique=False)
    op.create_index(op.f("ix_deadlines_filing_id"), "deadlines", ["filing_id"], unique=False)
    op.create_index(
        "ix_deadlines_org_created", "deadlines", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_deadlines_org_due", "deadlines", ["organization_id", "due_date"], unique=False
    )
    op.create_index(
        op.f("ix_deadlines_organization_id"), "deadlines", ["organization_id"], unique=False
    )
    op.create_index("ix_deadlines_sweep", "deadlines", ["is_satisfied", "due_date"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "REGULATORY_NOTICE",
                "CIRCULAR",
                "SHOW_CAUSE_NOTICE",
                "FILING_ATTACHMENT",
                "GENERATED_FILING",
                "CONSENT_RECORD",
                "OTHER",
                name="documenttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("filing_id", sa.Integer(), nullable=True),
        sa.Column(
            "regulation",
            sa.Enum(
                "GST",
                "INCOME_TAX",
                "RBI",
                "SEBI",
                "MCA",
                "FEMA",
                "LABOR",
                "DPDP",
                name="regulation",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "parse_status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "PARSED",
                "FAILED",
                name="parsestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("parsed_content", sa.Text(), nullable=True),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_method", sa.String(length=32), nullable=True),
        sa.Column(
            "extracted_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("extracted_deadline", sa.Date(), nullable=True),
        sa.Column("extracted_summary", sa.Text(), nullable=True),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_documents_extracted_deadline"), "documents", ["extracted_deadline"], unique=False
    )
    op.create_index(op.f("ix_documents_filing_id"), "documents", ["filing_id"], unique=False)
    op.create_index(
        "ix_documents_org_created", "documents", ["organization_id", "created_at"], unique=False
    )
    op.create_index("ix_documents_org_type", "documents", ["organization_id", "type"], unique=False)
    op.create_index(
        op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_documents_parse_queue", "documents", ["parse_status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_documents_parse_status"), "documents", ["parse_status"], unique=False)
    op.create_index(op.f("ix_documents_regulation"), "documents", ["regulation"], unique=False)
    op.create_index(op.f("ix_documents_type"), "documents", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_regulation"), table_name="documents")
    op.drop_index(op.f("ix_documents_parse_status"), table_name="documents")
    op.drop_index("ix_documents_parse_queue", table_name="documents")
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_index("ix_documents_org_type", table_name="documents")
    op.drop_index("ix_documents_org_created", table_name="documents")
    op.drop_index(op.f("ix_documents_filing_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_extracted_deadline"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_deadlines_sweep", table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_organization_id"), table_name="deadlines")
    op.drop_index("ix_deadlines_org_due", table_name="deadlines")
    op.drop_index("ix_deadlines_org_created", table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_filing_id"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_due_date"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_deleted_at"), table_name="deadlines")
    op.drop_table("deadlines")
    op.drop_index("ix_client_assignments_user_org", table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_user_id"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_deleted_at"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_client_org_id"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_client_id"), table_name="client_assignments")
    op.drop_table("client_assignments")
    op.drop_index(op.f("ix_regulatory_impacts_update_id"), table_name="regulatory_impacts")
    op.drop_index(op.f("ix_regulatory_impacts_organization_id"), table_name="regulatory_impacts")
    op.drop_index("ix_regulatory_impacts_org_created", table_name="regulatory_impacts")
    op.drop_index(op.f("ix_regulatory_impacts_impact_level"), table_name="regulatory_impacts")
    op.drop_index(op.f("ix_regulatory_impacts_deleted_at"), table_name="regulatory_impacts")
    op.drop_index("ix_impacts_org_open", table_name="regulatory_impacts")
    op.drop_index("ix_impacts_org_level", table_name="regulatory_impacts")
    op.drop_table("regulatory_impacts")
    op.drop_index(
        op.f("ix_privacy_impact_assessments_status"), table_name="privacy_impact_assessments"
    )
    op.drop_index(
        op.f("ix_privacy_impact_assessments_organization_id"),
        table_name="privacy_impact_assessments",
    )
    op.drop_index(
        "ix_privacy_impact_assessments_org_created", table_name="privacy_impact_assessments"
    )
    op.drop_index(
        op.f("ix_privacy_impact_assessments_deleted_at"), table_name="privacy_impact_assessments"
    )
    op.drop_index("ix_pia_org_status", table_name="privacy_impact_assessments")
    op.drop_table("privacy_impact_assessments")
    op.drop_index(
        op.f("ix_organization_obligations_owner_user_id"), table_name="organization_obligations"
    )
    op.drop_index(
        op.f("ix_organization_obligations_organization_id"), table_name="organization_obligations"
    )
    op.drop_index(
        op.f("ix_organization_obligations_obligation_id"), table_name="organization_obligations"
    )
    op.drop_index(
        op.f("ix_organization_obligations_deleted_at"), table_name="organization_obligations"
    )
    op.drop_index("ix_org_obligations_org_created", table_name="organization_obligations")
    op.drop_table("organization_obligations")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index("ix_notifications_retry", table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_index("ix_notifications_org_status", table_name="notifications")
    op.drop_index("ix_notifications_org_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_kind"), table_name="notifications")
    op.drop_index("ix_notifications_entity", table_name="notifications")
    op.drop_index(op.f("ix_notifications_deleted_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_channel"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_index(
        op.f("ix_notification_preferences_organization_id"), table_name="notification_preferences"
    )
    op.drop_index("ix_notification_preferences_org_created", table_name="notification_preferences")
    op.drop_index(
        op.f("ix_notification_preferences_deleted_at"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_filings_template_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_status"), table_name="filings")
    op.drop_index(op.f("ix_filings_reviewed_by_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_regulation"), table_name="filings")
    op.drop_index(op.f("ix_filings_prepared_by_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_period_key"), table_name="filings")
    op.drop_index(op.f("ix_filings_organization_id"), table_name="filings")
    op.drop_index("ix_filings_org_status_due", table_name="filings")
    op.drop_index("ix_filings_org_due", table_name="filings")
    op.drop_index("ix_filings_org_created", table_name="filings")
    op.drop_index(op.f("ix_filings_obligation_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_filing_type"), table_name="filings")
    op.drop_index(op.f("ix_filings_due_date"), table_name="filings")
    op.drop_index(op.f("ix_filings_deleted_at"), table_name="filings")
    op.drop_index(op.f("ix_filings_acknowledgement_no"), table_name="filings")
    op.drop_table("filings")
    op.drop_index("ix_dsr_org_status_due", table_name="data_subject_requests")
    op.drop_index(op.f("ix_data_subject_requests_status"), table_name="data_subject_requests")
    op.drop_index(op.f("ix_data_subject_requests_request_type"), table_name="data_subject_requests")
    op.drop_index(
        op.f("ix_data_subject_requests_principal_fingerprint"), table_name="data_subject_requests"
    )
    op.drop_index(
        op.f("ix_data_subject_requests_organization_id"), table_name="data_subject_requests"
    )
    op.drop_index("ix_data_subject_requests_org_created", table_name="data_subject_requests")
    op.drop_index(op.f("ix_data_subject_requests_due_date"), table_name="data_subject_requests")
    op.drop_index(op.f("ix_data_subject_requests_deleted_at"), table_name="data_subject_requests")
    op.drop_index(
        op.f("ix_data_subject_requests_assigned_to_id"), table_name="data_subject_requests"
    )
    op.drop_table("data_subject_requests")
    op.drop_index("ix_clients_firm_status", table_name="clients")
    op.drop_index(op.f("ix_clients_deleted_at"), table_name="clients")
    op.drop_index(op.f("ix_clients_client_org_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_ca_firm_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_assigned_user_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_breach_org_status", table_name="breach_incidents")
    op.drop_index("ix_breach_org_detected", table_name="breach_incidents")
    op.drop_index(op.f("ix_breach_incidents_status"), table_name="breach_incidents")
    op.drop_index(op.f("ix_breach_incidents_organization_id"), table_name="breach_incidents")
    op.drop_index("ix_breach_incidents_org_created", table_name="breach_incidents")
    op.drop_index(op.f("ix_breach_incidents_deleted_at"), table_name="breach_incidents")
    op.drop_table("breach_incidents")
    op.drop_index(op.f("ix_audit_trails_user_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_timestamp"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_request_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_organization_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_entity_type"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_entity_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_checksum"), table_name="audit_trails")
    op.drop_index(op.f("ix_audit_trails_action"), table_name="audit_trails")
    op.drop_index("ix_audit_org_timestamp", table_name="audit_trails")
    op.drop_index("ix_audit_org_sequence", table_name="audit_trails")
    op.drop_index("ix_audit_org_entity", table_name="audit_trails")
    op.drop_table("audit_trails")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index("ix_users_org_role", table_name="users")
    op.drop_index("ix_users_org_created", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_templates_regulation_active", table_name="templates")
    op.drop_index(op.f("ix_templates_regulation"), table_name="templates")
    op.drop_index(op.f("ix_templates_organization_id"), table_name="templates")
    op.drop_index("ix_templates_lookup", table_name="templates")
    op.drop_index(op.f("ix_templates_filing_type"), table_name="templates")
    op.drop_index(op.f("ix_templates_deleted_at"), table_name="templates")
    op.drop_index(op.f("ix_templates_code"), table_name="templates")
    op.drop_table("templates")
    op.drop_index("ix_datamap_org_sensitive", table_name="data_map_entries")
    op.drop_index(op.f("ix_data_map_entries_organization_id"), table_name="data_map_entries")
    op.drop_index("ix_data_map_entries_org_created", table_name="data_map_entries")
    op.drop_index(op.f("ix_data_map_entries_deleted_at"), table_name="data_map_entries")
    op.drop_index(op.f("ix_data_map_entries_data_category"), table_name="data_map_entries")
    op.drop_table("data_map_entries")
    op.drop_index(op.f("ix_consent_records_purpose"), table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_principal_fingerprint"), table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_organization_id"), table_name="consent_records")
    op.drop_index("ix_consent_records_org_created", table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_deleted_at"), table_name="consent_records")
    op.drop_index("ix_consent_org_principal", table_name="consent_records")
    op.drop_index("ix_consent_org_active", table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index("ix_obligations_regulation_active", table_name="compliance_obligations")
    op.drop_index(op.f("ix_compliance_obligations_regulation"), table_name="compliance_obligations")
    op.drop_index(
        op.f("ix_compliance_obligations_organization_id"), table_name="compliance_obligations"
    )
    op.drop_index(
        op.f("ix_compliance_obligations_filing_type"), table_name="compliance_obligations"
    )
    op.drop_index(op.f("ix_compliance_obligations_deleted_at"), table_name="compliance_obligations")
    op.drop_index(op.f("ix_compliance_obligations_code"), table_name="compliance_obligations")
    op.drop_table("compliance_obligations")
    op.drop_index(op.f("ix_regulatory_updates_source"), table_name="regulatory_updates")
    op.drop_index(op.f("ix_regulatory_updates_regulation"), table_name="regulatory_updates")
    op.drop_index(op.f("ix_regulatory_updates_reference_no"), table_name="regulatory_updates")
    op.drop_index(op.f("ix_regulatory_updates_published_date"), table_name="regulatory_updates")
    op.drop_index(op.f("ix_regulatory_updates_impact_level"), table_name="regulatory_updates")
    op.drop_index(op.f("ix_regulatory_updates_deleted_at"), table_name="regulatory_updates")
    op.drop_index("ix_reg_updates_published", table_name="regulatory_updates")
    op.drop_index("ix_reg_updates_pending", table_name="regulatory_updates")
    op.drop_table("regulatory_updates")
    op.drop_index("ix_organizations_type_active", table_name="organizations")
    op.drop_index(op.f("ix_organizations_state"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_pan_fingerprint"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_industry"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_gstin_fingerprint"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_cin_fingerprint"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
